export const marketDataItems = [
  {
    id: 1,
    name: 'iPhone 14 Pro Max',
    price: '999',
    location: 'Lahore, Pakistan',
    image: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg',
  },
  {
    id: 2,
    name: 'Gaming Laptop',
    price: '1200',
    location: 'Karachi, Pakistan',
    image: 'https://m.media-amazon.com/images/I/71vFKBpKakL._AC_SL1500_.jpg',
  },
  {
    id: 3,
    name: 'Mountain Bike',
    price: '450',
    location: 'Islamabad, Pakistan',
    image: 'https://images.unsplash.com/photo-1508780709619-79562169bc64',
  },
  {
    id: 4,
    name: 'Smart Watch',
    price: '200',
    location: 'Rawalpindi, Pakistan',
    image: 'https://m.media-amazon.com/images/I/71g2ednj0JL._AC_SL1500_.jpg',
  },
  {
    id: 5,
    name: 'Leather Sofa',
    price: '750',
    location: 'Faisalabad, Pakistan',
    image: 'https://images.unsplash.com/photo-1616627989399-1f1e4b8b6f0a',
  },
  {
    id: 6,
    name: 'DSLR Camera',
    price: '550',
    location: 'Multan, Pakistan',
    image: 'https://m.media-amazon.com/images/I/81tK5U8zYGL._AC_SL1500_.jpg',
  },
  {
    id: 7,
    name: 'Air Conditioner',
    price: '600',
    location: 'Gujranwala, Pakistan',
    image: 'https://images.unsplash.com/photo-1598300055409-0b4a6f3b7f1d',
  },
  {
    id: 8,
    name: 'Refrigerator',
    price: '800',
    location: 'Hyderabad, Pakistan',
    image: 'https://m.media-amazon.com/images/I/71b0w3YbKkL._AC_SL1500_.jpg',
  },
  {
    id: 9,
    name: 'LED TV 50"',
    price: '500',
    location: 'Peshawar, Pakistan',
    image: 'https://m.media-amazon.com/images/I/81r8JazBv-L._AC_SL1500_.jpg',
  },
  {
    id: 10,
    name: 'Electric Bike',
    price: '950',
    location: 'Quetta, Pakistan',
    image: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6',
  },
];
