export const marketDataItems = [
  {
    id: 1,
    name: 'iPhone 14 Pro Max',
    price: '999',
    location: 'Lahore, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=iPhone+14+Pro+Max',
  },
  {
    id: 2,
    name: 'Gaming Laptop',
    price: '1200',
    location: 'Karachi, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Gaming+Laptop',
  },
  {
    id: 3,
    name: 'Mountain Bike',
    price: '450',
    location: 'Islamabad, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Mountain+Bike',
  },
  {
    id: 4,
    name: 'Smart Watch',
    price: '200',
    location: 'Rawalpindi, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Smart+Watch',
  },
  {
    id: 5,
    name: 'Leather Sofa',
    price: '750',
    location: 'Faisalabad, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Leather+Sofa',
  },
  {
    id: 6,
    name: 'DSLR Camera',
    price: '550',
    location: 'Multan, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=DSLR+Camera',
  },
  {
    id: 7,
    name: 'Air Conditioner',
    price: '600',
    location: 'Gujranwala, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Air+Conditioner',
  },
  {
    id: 8,
    name: 'Refrigerator',
    price: '800',
    location: 'Hyderabad, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Refrigerator',
  },
  {
    id: 9,
    name: 'LED TV 50"',
    price: '500',
    location: 'Peshawar, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=LED+TV+50+inch',
  },
  {
    id: 10,
    name: 'Electric Bike',
    price: '950',
    location: 'Quetta, Pakistan',
    image: 'https://via.placeholder.com/400x300?text=Electric+Bike',
  },
];
