export const sidebar_data = [
  {
    id: 1,
    icon: "/menu_icons/friends.png",
    title: "Friends",
    link: "/friends",
  },
  {
    id: 2,
    icon: "/menu_icons/memory.png",
    title: "Memories",
    link: "/memories",
  },
  {
    id: 3,
    icon: "/menu_icons/saved.png",
    title: "Saved",
    link: "/saved",
  },
  {
    id: 4,
    icon: "/menu_icons/groups.png",
    title: "Groups",
    link: "/groups",
  },
  {
    id: 5,
    icon: "/menu_icons/video.png",
    title: "Video",
    link: "/video",
  },
  {
    id: 6,
    icon: "/menu_icons/marketplace.png",
    title: "Marketplace",
    link: "/marketplace",
  },
  {
    id: 7,
    icon: "/menu_icons/feed.png",
    title: "Feeds",
    link: "/feeds",
  },
  {
    id: 8,
    icon: "/menu_icons/events.png",
    title: "Events",
    link: "/events",
  },
  {
    id: 9,
    icon: "/menu_icons/ads.png",
    title: "Ads Manager",
    link: "/ads-manager",
  },
  {
    id: 10,
    icon: "/menu_icons/fundraisers.png",
    title: "Fundraisers",
    link: "/fundraisers",
  },
  {
    id: 11,
    icon: "/menu_icons/birthday.png",
    title: "Birthdays",
    link: "/birthdays",
  },
  {
    id: 12,
    icon: "/menu_icons/climate.png",
    title: "Climate Science Centre",
    link: "/climatecenterinfo",
  },
  {
    id: 13,
    icon: "/menu_icons/gaming.png",
    title: "Gaming video",
    link: "/gaming-video",
  },
  {
    id: 14,
    icon: "/menu_icons/messenger1.png",
    title: "Messenger",
    link: "/messenger",
  },
  {
    id: 15,
    icon: "/menu_icons/kids.png",
    title: "Messenger Kids",
    link: "/messenger-kids",
  },
  {
    id: 16,
    icon: "/menu_icons/order.png",
    title: "Orders and payments",
    link: "/orders-and-payments",
  },
  {
    id: 17,
    icon: "/menu_icons/pages.png",
    title: "Pages",
    link: "/pages",
  },
  {
    id: 18,
    icon: "/menu_icons/play.png",
    title: "Play games",
    link: "/play-games",
  },
  {
    id: 19,
    icon: "/menu_icons/recent_ad.png",
    title: "Recent ad activity",
    link: "/recent-ad-activity",
  },
  {
    id: 20,
    icon: "/menu_icons/reels.png",
    title: "Reels",
    link: "/reels",
  },
];
